// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (
    cart_id,
    variant_id,
    quantity
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (cart_id, variant_id)
DO UPDATE
SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    updated_at = NOW()
RETURNING
    id,
    cart_id,
    variant_id,
    quantity,
    created_at,
    updated_at
`

type AddCartItemParams struct {
	CartID    pgtype.UUID
	VariantID pgtype.UUID
	Quantity  int64
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem, arg.CartID, arg.VariantID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const convertCart = `-- name: ConvertCart :one
UPDATE carts
SET
    status = 'CONVERTED',
    updated_at = NOW()
WHERE id = $1
  AND status = 'ACTIVE'
RETURNING
    id,
    status,
    created_at,
    updated_at
`

func (q *Queries) ConvertCart(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, convertCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
    status
)
VALUES (
    'ACTIVE'
)
RETURNING
    id,
    status,
    created_at,
    updated_at
`

func (q *Queries) CreateCart(ctx context.Context) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCart = `-- name: GetActiveCart :one
SELECT
    id,
    status,
    created_at,
    updated_at
FROM carts
WHERE id = $1
  AND status = 'ACTIVE'
`

func (q *Queries) GetActiveCart(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getActiveCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCart = `-- name: GetCart :one
SELECT
    id,
    status,
    created_at,
    updated_at
FROM carts
WHERE id = $1
`

func (q *Queries) GetCart(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT
    id,
    cart_id,
    variant_id,
    quantity,
    created_at,
    updated_at
FROM cart_items
WHERE cart_id = $1
  AND variant_id = $2
`

type GetCartItemParams struct {
	CartID    pgtype.UUID
	VariantID pgtype.UUID
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, arg.CartID, arg.VariantID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT
    id,
    cart_id,
    variant_id,
    quantity,
    created_at,
    updated_at
FROM cart_items
WHERE cart_id = $1
ORDER BY created_at
`

func (q *Queries) GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.VariantID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE cart_id = $1
  AND variant_id = $2
`

type RemoveCartItemParams struct {
	CartID    pgtype.UUID
	VariantID pgtype.UUID
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.CartID, arg.VariantID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET
    quantity = $3,
    updated_at = NOW()
WHERE cart_id = $1
  AND variant_id = $2
RETURNING
    id,
    cart_id,
    variant_id,
    quantity,
    created_at,
    updated_at
`

type UpdateCartItemQuantityParams struct {
	CartID    pgtype.UUID
	VariantID pgtype.UUID
	Quantity  int64
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.CartID, arg.VariantID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
