// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    description
)
VALUES ($1, $2)
RETURNING
    id,
    name,
    description,
    created_at,
    updated_at
`

type CreateProductParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Description)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
    product_id,
    sku,
    size,
    color,
    price
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id,
    product_id,
    sku,
    size,
    color,
    price,
    created_at,
    updated_at
`

type CreateProductVariantParams struct {
	ProductID pgtype.UUID
	Sku       string
	Size      pgtype.Text
	Color     pgtype.Text
	Price     int64
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.Sku,
		arg.Size,
		arg.Color,
		arg.Price,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Size,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT
    id,
    product_id,
    sku,
    size,
    color,
    price,
    created_at,
    updated_at
FROM product_variants
WHERE id = $1
`

func (q *Queries) GetProductVariant(ctx context.Context, id pgtype.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getProductVariant, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Size,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT
    id,
    product_id,
    sku,
    size,
    color,
    price,
    created_at,
    updated_at
FROM product_variants
WHERE product_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProductVariants(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Size,
			&i.Color,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM products
ORDER BY created_at DESC, id DESC
LIMIT $1
OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsAsc = `-- name: ListProductsAsc :many
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM products
ORDER BY created_at ASC, id ASC
LIMIT $1
OFFSET $2
`

type ListProductsAscParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsAsc(ctx context.Context, arg ListProductsAscParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPriceAsc = `-- name: ListProductsPriceAsc :many
SELECT
    p.id,
    p.name,
    p.description,
    p.created_at,
    p.updated_at
FROM products p
JOIN product_variants pv
    ON pv.product_id = p.id
GROUP BY
    p.id,
    p.name,
    p.description,
    p.created_at,
    p.updated_at
ORDER BY MIN(pv.price) ASC, p.id ASC
LIMIT $1
OFFSET $2
`

type ListProductsPriceAscParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsPriceAsc(ctx context.Context, arg ListProductsPriceAscParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsPriceAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPriceDesc = `-- name: ListProductsPriceDesc :many
SELECT
    p.id,
    p.name,
    p.description,
    p.created_at,
    p.updated_at
FROM products p
JOIN product_variants pv
    ON pv.product_id = p.id
GROUP BY
    p.id,
    p.name,
    p.description,
    p.created_at,
    p.updated_at
ORDER BY MIN(pv.price) DESC, p.id DESC
LIMIT $1
OFFSET $2
`

type ListProductsPriceDescParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsPriceDesc(ctx context.Context, arg ListProductsPriceDescParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsPriceDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM products
WHERE name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type SearchProductsParams struct {
	SearchTerm pgtype.Text
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.SearchTerm, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
