// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consumer_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordConsumerEvent = `-- name: RecordConsumerEvent :one
INSERT INTO consumer_events (
    consumer_name,
    event_id
)
VALUES (
    $1,
    $2
)
ON CONFLICT (consumer_name, event_id) DO NOTHING
RETURNING
    id,
    consumer_name,
    event_id,
    processed_at
`

type RecordConsumerEventParams struct {
	ConsumerName string
	EventID      pgtype.UUID
}

func (q *Queries) RecordConsumerEvent(ctx context.Context, arg RecordConsumerEventParams) (ConsumerEvent, error) {
	row := q.db.QueryRow(ctx, recordConsumerEvent, arg.ConsumerName, arg.EventID)
	var i ConsumerEvent
	err := row.Scan(
		&i.ID,
		&i.ConsumerName,
		&i.EventID,
		&i.ProcessedAt,
	)
	return i, err
}
