// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventory = `-- name: GetInventory :one
SELECT
    i.variant_id,
    i.quantity,
    COALESCE(
        SUM(
            CASE
                WHEN r.status = 'ACTIVE'
                 AND r.expires_at > NOW()
                THEN r.quantity
                ELSE 0
            END
        ),
        0
    )::BIGINT AS reserved_quantity,
    (
        i.quantity -
        COALESCE(
            SUM(
                CASE
                    WHEN r.status = 'ACTIVE'
                     AND r.expires_at > NOW()
                    THEN r.quantity
                    ELSE 0
                END
            ),
            0
        )::BIGINT
    )::BIGINT AS available_quantity
FROM inventory i
LEFT JOIN reservations r
    ON r.variant_id = i.variant_id
WHERE i.variant_id = $1
GROUP BY
    i.variant_id,
    i.quantity
`

type GetInventoryRow struct {
	VariantID         pgtype.UUID
	Quantity          int64
	ReservedQuantity  int64
	AvailableQuantity int64
}

func (q *Queries) GetInventory(ctx context.Context, variantID pgtype.UUID) (GetInventoryRow, error) {
	row := q.db.QueryRow(ctx, getInventory, variantID)
	var i GetInventoryRow
	err := row.Scan(
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.AvailableQuantity,
	)
	return i, err
}
