// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_movements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (
    variant_id,
    movement_type,
    quantity,
    reference_type,
    reference_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id,
    variant_id,
    movement_type,
    quantity,
    reference_type,
    reference_id,
    created_at
`

type CreateInventoryMovementParams struct {
	VariantID     pgtype.UUID
	MovementType  string
	Quantity      int64
	ReferenceType pgtype.Text
	ReferenceID   pgtype.UUID
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.VariantID,
		arg.MovementType,
		arg.Quantity,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.MovementType,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const listInventoryMovements = `-- name: ListInventoryMovements :many
SELECT
    id,
    variant_id,
    movement_type,
    quantity,
    reference_type,
    reference_id,
    created_at
FROM inventory_movements
WHERE variant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInventoryMovements(ctx context.Context, variantID pgtype.UUID) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listInventoryMovements, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.MovementType,
			&i.Quantity,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
