// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ID        pgtype.UUID
	VariantID pgtype.UUID
	Quantity  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OutboxEvent struct {
	ID              pgtype.UUID
	EventType       string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
	LastAttemptedAt pgtype.Timestamptz
	Attempts        int32
	Status          string
	ProcessingAt    pgtype.Timestamptz
}

type Product struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProductVariant struct {
	ID        pgtype.UUID
	ProductID pgtype.UUID
	Sku       string
	Size      pgtype.Text
	Color     pgtype.Text
	Price     int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Reservation struct {
	ID        pgtype.UUID
	VariantID pgtype.UUID
	OrderID   pgtype.UUID
	Quantity  int64
	Status    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
