// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CartItem struct {
	ID        pgtype.UUID
	CartID    pgtype.UUID
	VariantID pgtype.UUID
	Quantity  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ConsumerEvent struct {
	ID           pgtype.UUID
	ConsumerName string
	EventID      pgtype.UUID
	ProcessedAt  pgtype.Timestamptz
}

type Inventory struct {
	ID        pgtype.UUID
	VariantID pgtype.UUID
	Quantity  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID          pgtype.UUID
	Status      string
	TotalAmount int64
	Currency    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type OrderItem struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	VariantID pgtype.UUID
	Quantity  int64
	UnitPrice int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OutboxEvent struct {
	ID              pgtype.UUID
	EventType       string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
	LastAttemptedAt pgtype.Timestamptz
	Attempts        int32
	Status          string
	ProcessingAt    pgtype.Timestamptz
}

type Payment struct {
	ID                pgtype.UUID
	ReservationID     pgtype.UUID
	Provider          string
	ProviderPaymentID pgtype.Text
	Amount            int64
	Currency          string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	OrderID           pgtype.UUID
}

type PaymentEvent struct {
	ID        pgtype.UUID
	EventID   string
	PaymentID pgtype.UUID
	EventType string
	CreatedAt pgtype.Timestamptz
}

type PaymentProcessing struct {
	ID          pgtype.UUID
	PaymentID   pgtype.UUID
	ProcessedAt pgtype.Timestamptz
}

type Product struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProductVariant struct {
	ID        pgtype.UUID
	ProductID pgtype.UUID
	Sku       string
	Size      pgtype.Text
	Color     pgtype.Text
	Price     int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Reservation struct {
	ID        pgtype.UUID
	VariantID pgtype.UUID
	OrderID   pgtype.UUID
	Quantity  int64
	Status    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
