// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
WITH claimed AS (
    SELECT id
    FROM outbox_events
    WHERE status = 'PENDING'
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS o
SET
    status = 'PROCESSING',
    processing_at = NOW(),
    processing_token = gen_random_uuid()
FROM claimed
WHERE o.id = claimed.id
RETURNING
    o.id,
    o.event_type,
    o.payload,
    o.created_at,
    o.published_at,
    o.last_attempted_at,
    o.attempts,
    o.status,
    o.processing_at,
    o.processing_token
`

func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context, batchSize int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOutboxEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.LastAttemptedAt,
			&i.Attempts,
			&i.Status,
			&i.ProcessingAt,
			&i.ProcessingToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    event_type,
    payload
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    event_type,
    payload,
    created_at,
    published_at,
    last_attempted_at,
    attempts,
    status,
    processing_at
`

type CreateOutboxEventParams struct {
	EventType string
	Payload   []byte
}

type CreateOutboxEventRow struct {
	ID              pgtype.UUID
	EventType       string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
	LastAttemptedAt pgtype.Timestamptz
	Attempts        int32
	Status          string
	ProcessingAt    pgtype.Timestamptz
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.Payload)
	var i CreateOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.LastAttemptedAt,
		&i.Attempts,
		&i.Status,
		&i.ProcessingAt,
	)
	return i, err
}

const deletePublishedOutboxEventsBefore = `-- name: DeletePublishedOutboxEventsBefore :execrows
WITH deletable AS (
    SELECT id
    FROM outbox_events
    WHERE outbox_events.status = 'PUBLISHED'
      AND outbox_events.published_at < $1
    ORDER BY outbox_events.published_at
    LIMIT $2
)
DELETE FROM outbox_events AS o
USING deletable
WHERE o.id = deletable.id
`

type DeletePublishedOutboxEventsBeforeParams struct {
	PublishedAt pgtype.Timestamptz
	Limit       int32
}

func (q *Queries) DeletePublishedOutboxEventsBefore(ctx context.Context, arg DeletePublishedOutboxEventsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutboxEventsBefore, arg.PublishedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT
    id,
    event_type,
    payload,
    created_at,
    published_at,
    last_attempted_at,
    attempts,
    status,
    processing_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at
`

type ListPendingOutboxEventsRow struct {
	ID              pgtype.UUID
	EventType       string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
	LastAttemptedAt pgtype.Timestamptz
	Attempts        int32
	Status          string
	ProcessingAt    pgtype.Timestamptz
}

func (q *Queries) ListPendingOutboxEvents(ctx context.Context) ([]ListPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEventsRow
	for rows.Next() {
		var i ListPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.LastAttemptedAt,
			&i.Attempts,
			&i.Status,
			&i.ProcessingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :execrows
UPDATE outbox_events
SET
    status = 'PUBLISHED',
    published_at = NOW(),
    processing_at = NULL,
    processing_token = NULL
WHERE id = $1
  AND status = 'PROCESSING'
  AND processing_token = $2
`

type MarkOutboxEventPublishedParams struct {
	ID              pgtype.UUID
	ProcessingToken pgtype.UUID
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventPublished, arg.ID, arg.ProcessingToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublishAttempt = `-- name: MarkOutboxPublishAttempt :execrows
UPDATE outbox_events
SET
    attempts = attempts + 1,
    last_attempted_at = NOW()
WHERE id = $1
  AND status = 'PROCESSING'
  AND processing_token = $2
`

type MarkOutboxPublishAttemptParams struct {
	ID              pgtype.UUID
	ProcessingToken pgtype.UUID
}

func (q *Queries) MarkOutboxPublishAttempt(ctx context.Context, arg MarkOutboxPublishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublishAttempt, arg.ID, arg.ProcessingToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverStaleOutboxEvents = `-- name: RecoverStaleOutboxEvents :exec
UPDATE outbox_events
SET
    status = 'PENDING',
    processing_at = NULL,
    processing_token = NULL
WHERE status = 'PROCESSING'
  AND processing_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) RecoverStaleOutboxEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverStaleOutboxEvents)
	return err
}
