// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
WITH claimed AS (
    SELECT id
    FROM outbox_events
    WHERE status = 'PENDING'
    ORDER BY created_at
    LIMIT 100
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS o
SET
    status = 'PROCESSING',
    processing_at = NOW()
FROM claimed
WHERE o.id = claimed.id
RETURNING
    o.id,
    o.event_type,
    o.payload,
    o.created_at,
    o.published_at,
    o.last_attempted_at,
    o.attempts,
    o.status,
    o.processing_at
`

func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.LastAttemptedAt,
			&i.Attempts,
			&i.Status,
			&i.ProcessingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT
    id,
    event_type,
    payload,
    created_at,
    published_at,
    last_attempted_at,
    attempts,
    status,
    processing_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.LastAttemptedAt,
			&i.Attempts,
			&i.Status,
			&i.ProcessingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET
    status = 'PUBLISHED',
    published_at = NOW()
WHERE id = $1
  AND status = 'PROCESSING'
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const markOutboxPublishAttempt = `-- name: MarkOutboxPublishAttempt :exec
UPDATE outbox_events
SET
    attempts = attempts + 1,
    last_attempted_at = NOW()
WHERE id = $1
  AND status = 'PROCESSING'
`

func (q *Queries) MarkOutboxPublishAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublishAttempt, id)
	return err
}
