// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordPaymentEvent = `-- name: RecordPaymentEvent :one
INSERT INTO payment_events (
    event_id,
    payment_id,
    event_type
)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, payment_id, event_type, created_at
`

type RecordPaymentEventParams struct {
	EventID   string
	PaymentID pgtype.UUID
	EventType string
}

func (q *Queries) RecordPaymentEvent(ctx context.Context, arg RecordPaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, recordPaymentEvent, arg.EventID, arg.PaymentID, arg.EventType)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PaymentID,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}
