// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_processing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentProcessing = `-- name: CreatePaymentProcessing :one
INSERT INTO payment_processing (
    payment_id
)
VALUES ($1)
RETURNING
    id,
    payment_id,
    processed_at
`

func (q *Queries) CreatePaymentProcessing(ctx context.Context, paymentID pgtype.UUID) (PaymentProcessing, error) {
	row := q.db.QueryRow(ctx, createPaymentProcessing, paymentID)
	var i PaymentProcessing
	err := row.Scan(&i.ID, &i.PaymentID, &i.ProcessedAt)
	return i, err
}

const getPaymentProcessing = `-- name: GetPaymentProcessing :one
SELECT
    id,
    payment_id,
    processed_at
FROM payment_processing
WHERE payment_id = $1
`

func (q *Queries) GetPaymentProcessing(ctx context.Context, paymentID pgtype.UUID) (PaymentProcessing, error) {
	row := q.db.QueryRow(ctx, getPaymentProcessing, paymentID)
	var i PaymentProcessing
	err := row.Scan(&i.ID, &i.PaymentID, &i.ProcessedAt)
	return i, err
}
