// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    provider,
    provider_payment_id,
    amount,
    currency,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, reservation_id, provider, provider_payment_id, amount, currency, status, created_at, updated_at, order_id
`

type CreatePaymentParams struct {
	OrderID           pgtype.UUID
	Provider          string
	ProviderPaymentID pgtype.Text
	Amount            int64
	Currency          string
	Status            string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT
    id,
    reservation_id,
    provider,
    provider_payment_id,
    amount,
    currency,
    status,
    created_at,
    updated_at,
    order_id
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET
    status = 'FAILED',
    updated_at = NOW()
WHERE id = $1
RETURNING id, reservation_id, provider, provider_payment_id, amount, currency, status, created_at, updated_at, order_id
`

func (q *Queries) MarkPaymentFailed(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
	)
	return i, err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE payments
SET
    status = 'SUCCEEDED',
    updated_at = NOW()
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, reservation_id, provider, provider_payment_id, amount, currency, status, created_at, updated_at, order_id
`

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
	)
	return i, err
}

const updatePaymentProviderID = `-- name: UpdatePaymentProviderID :one
UPDATE payments
SET
    provider_payment_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, reservation_id, provider, provider_payment_id, amount, currency, status, created_at, updated_at, order_id
`

type UpdatePaymentProviderIDParams struct {
	ID                pgtype.UUID
	ProviderPaymentID pgtype.Text
}

func (q *Queries) UpdatePaymentProviderID(ctx context.Context, arg UpdatePaymentProviderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentProviderID, arg.ID, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
	)
	return i, err
}
