// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refunds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (
    payment_id,
    amount,
    currency,
    status,
    idempotency_key
)
VALUES (
    $1,
    $2,
    $3,
    'PENDING',
    $4
)
RETURNING id, payment_id, provider_refund_id, amount, currency, status, idempotency_key, created_at, updated_at
`

type CreateRefundParams struct {
	PaymentID      pgtype.UUID
	Amount         int64
	Currency       string
	IdempotencyKey string
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.PaymentID,
		arg.Amount,
		arg.Currency,
		arg.IdempotencyKey,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ProviderRefundID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, payment_id, provider_refund_id, amount, currency, status, idempotency_key, created_at, updated_at
FROM refunds
WHERE id = $1
`

func (q *Queries) GetRefund(ctx context.Context, id pgtype.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefund, id)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ProviderRefundID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByIdempotencyKey = `-- name: GetRefundByIdempotencyKey :one
SELECT id, payment_id, provider_refund_id, amount, currency, status, idempotency_key, created_at, updated_at
FROM refunds
WHERE idempotency_key = $1
`

func (q *Queries) GetRefundByIdempotencyKey(ctx context.Context, idempotencyKey string) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByIdempotencyKey, idempotencyKey)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ProviderRefundID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByPaymentID = `-- name: GetRefundByPaymentID :one
SELECT id, payment_id, provider_refund_id, amount, currency, status, idempotency_key, created_at, updated_at
FROM refunds
WHERE payment_id = $1
`

func (q *Queries) GetRefundByPaymentID(ctx context.Context, paymentID pgtype.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByPaymentID, paymentID)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ProviderRefundID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRefundFailed = `-- name: MarkRefundFailed :one
UPDATE refunds
SET
    status = 'FAILED',
    updated_at = NOW()
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, payment_id, provider_refund_id, amount, currency, status, idempotency_key, created_at, updated_at
`

func (q *Queries) MarkRefundFailed(ctx context.Context, id pgtype.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, markRefundFailed, id)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ProviderRefundID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRefundSucceeded = `-- name: MarkRefundSucceeded :one
UPDATE refunds
SET
    status = 'SUCCEEDED',
    provider_refund_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, payment_id, provider_refund_id, amount, currency, status, idempotency_key, created_at, updated_at
`

type MarkRefundSucceededParams struct {
	ID               pgtype.UUID
	ProviderRefundID pgtype.Text
}

func (q *Queries) MarkRefundSucceeded(ctx context.Context, arg MarkRefundSucceededParams) (Refund, error) {
	row := q.db.QueryRow(ctx, markRefundSucceeded, arg.ID, arg.ProviderRefundID)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ProviderRefundID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
