// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    variant_id,
    order_id,
    quantity,
    status,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    'ACTIVE',
    $4
)
RETURNING
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
`

type CreateReservationParams struct {
	VariantID pgtype.UUID
	OrderID   pgtype.UUID
	Quantity  int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.VariantID,
		arg.OrderID,
		arg.Quantity,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReservedQuantity = `-- name: GetActiveReservedQuantity :one
SELECT
    COALESCE(SUM(quantity), 0)::BIGINT AS reserved_quantity
FROM reservations
WHERE variant_id = $1
  AND status = 'ACTIVE'
  AND expires_at > NOW()
`

func (q *Queries) GetActiveReservedQuantity(ctx context.Context, variantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveReservedQuantity, variantID)
	var reserved_quantity int64
	err := row.Scan(&reserved_quantity)
	return reserved_quantity, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT
    id,
    variant_id,
    quantity,
    created_at,
    updated_at
FROM inventory
WHERE variant_id = $1
FOR UPDATE
`

func (q *Queries) GetInventoryForUpdate(ctx context.Context, variantID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryForUpdate, variantID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
