// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReservation = `-- name: CancelReservation :one
UPDATE reservations
SET
    status = 'CANCELLED',
    updated_at = NOW()
WHERE id = $1
  AND status = 'ACTIVE'
RETURNING
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
`

func (q *Queries) CancelReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, cancelReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmReservation = `-- name: ConfirmReservation :one
UPDATE reservations
SET
    status = 'CONFIRMED',
    updated_at = NOW()
WHERE id = $1
  AND status = 'ACTIVE'
  AND expires_at > NOW()
RETURNING
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
`

func (q *Queries) ConfirmReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, confirmReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeInventory = `-- name: ConsumeInventory :one
UPDATE inventory
SET
    quantity = quantity - $2,
    updated_at = NOW()
WHERE variant_id = $1
  AND quantity >= $2
RETURNING
    id,
    variant_id,
    quantity,
    created_at,
    updated_at
`

type ConsumeInventoryParams struct {
	VariantID pgtype.UUID
	Quantity  int64
}

func (q *Queries) ConsumeInventory(ctx context.Context, arg ConsumeInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, consumeInventory, arg.VariantID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    variant_id,
    order_id,
    quantity,
    status,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    'ACTIVE',
    $4
)
RETURNING
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
`

type CreateReservationParams struct {
	VariantID pgtype.UUID
	OrderID   pgtype.UUID
	Quantity  int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.VariantID,
		arg.OrderID,
		arg.Quantity,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireExpiredReservations = `-- name: ExpireExpiredReservations :many
WITH expired AS (
    SELECT id
    FROM reservations
    WHERE status = 'ACTIVE'
      AND expires_at <= NOW()
    ORDER BY expires_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE reservations AS r
SET
    status = 'EXPIRED',
    updated_at = NOW()
FROM expired
WHERE r.id = expired.id
RETURNING
    r.id,
    r.variant_id,
    r.order_id,
    r.quantity,
    r.status,
    r.expires_at,
    r.created_at,
    r.updated_at
`

func (q *Queries) ExpireExpiredReservations(ctx context.Context, limit int32) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, expireExpiredReservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.OrderID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireReservation = `-- name: ExpireReservation :one
UPDATE reservations
SET
    status = 'EXPIRED',
    updated_at = NOW()
WHERE id = $1
  AND status = 'ACTIVE'
  AND expires_at <= NOW()
RETURNING
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
`

func (q *Queries) ExpireReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, expireReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReservationsByOrderID = `-- name: GetActiveReservationsByOrderID :many
SELECT
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE order_id = $1
  AND status = 'ACTIVE'
ORDER BY created_at
`

func (q *Queries) GetActiveReservationsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getActiveReservationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.OrderID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveReservedQuantity = `-- name: GetActiveReservedQuantity :one
SELECT
    COALESCE(SUM(quantity), 0)::BIGINT AS reserved_quantity
FROM reservations
WHERE variant_id = $1
  AND status = 'ACTIVE'
  AND expires_at > NOW()
`

func (q *Queries) GetActiveReservedQuantity(ctx context.Context, variantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveReservedQuantity, variantID)
	var reserved_quantity int64
	err := row.Scan(&reserved_quantity)
	return reserved_quantity, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT
    id,
    variant_id,
    quantity,
    created_at,
    updated_at
FROM inventory
WHERE variant_id = $1
FOR UPDATE
`

func (q *Queries) GetInventoryForUpdate(ctx context.Context, variantID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryForUpdate, variantID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationsByOrderID = `-- name: GetReservationsByOrderID :many
SELECT
    id,
    variant_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) GetReservationsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getReservationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.OrderID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
